title: Daniel Saad
logo: https://avatars.githubusercontent.com/u/2043876?v=4
email: daniel.nunes@ifb.edu.br
description:
show_downloads: false
google_analytics: UA-91631229-1
color-scheme: auto
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji

# You can find fonts from https://iconify.design or https://fontawesome.com. Below is just an example illustrating how to use custom icons
sidebar:
  - name: Ensino
    icon: <i class="fa-solid fa-chalkboard-user"></i>
    link: /ensino
  - name: Extensão
    icon: <i class='fas fa-globe'></i>	
    link: /extensao
  - name: Pesquisa
    icon: <i class='fas fa-project-diagram'></i>
    link: /pesquisa
  - name: Estudantes
    icon: <i class='fas fa-user-graduate'></i>
    link: /estudantes
  - name: Contato
    icon: <i class='fas fa-user-circle'></i>	
    link: /contato

# https://github.com/github/pages-gem/issues/399#issuecomment-301827749
# When running locally, we run into the following error —
# GitHub Metadata: No GitHub API authentication could be found. Some fields may be missing or have incorrect data.
# adding this avoids it
github: [metadata]
