---
title: Daniel Saad Nogueira Nunes
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: daniel.saad.nunes@gmail.com
description: Página Pessoal
baseurl: ''
url: ''
github_username: danielsaad
show_downloads: true
paginate: 5
paginate_path: "/posts/page:num/"
markdown: kramdown
theme: minima
gems:
- jekyll-feed
- octopress-paginate
exclude:
- Gemfile
- Gemfile.lock
